services:
  minio-alone:
    container_name: minio-alone
    hostname: minio-alone
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    volumes:
      - ./minio-data:/data
    command: ["server", "/data", "--console-address", ":9001"]
    networks:
      - addms_net

networks:
  addms_net:
    name: addms_net
    external: true